---
title: "İzmir Büyükşehir Belediyesi Taşıt Genel Biniş Raporları Üzerine Tahmin"
author: 
  - Selin Uysal[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 21080216, [Github Repo](https://github.com/selinuysal26/arasinav)

# Giriş
İzmir, Türkiye'de Ege Bölgesi'nde yer alan şehir ve ülkenin 81 ilinden biridir. Ülkenin nüfus bakımından en kalabalık üçüncü şehridir. Ekonomik, tarihi ve sosyo-kültürel açıdan önde gelen şehirlerden biridir. Nüfusu 2022 itibarıyla 4.462.056 kişidir. Yüzölçümü olarak ülkenin yirmi üçüncü büyük ilidir. Tarafı Aydın, Balıkesir, Manisa illeri ve Ege Denizi ve Ege Adaları ile çevrilidir (@Wikipedia:2023).

Toplu taşımacılık veya kamu taşımacılığı, kişisel araç kullanılmadan yapılan yolculuklar için kullanılan tüm ulaşım sistemlerine verilen genel addır. Bazı özel insanlar için ücretsiz toplu taşıma hizmeti mevcuttur. Özel ulaşım ve paylaşımlı ulaşımdan farklı, tipik olarak bir tarifeye göre yönetilen, belirlenmiş güzergahlarda işletilen ve her yolculuk için ilan edilen bir ücret vardır.[1] Bu taşıma sisteminde birden fazla yolcu taşınmakla, enerji tasarrufu yapılır. Toplu taşımacılık, şehir içi ve şehirlerarası olabilir. Toplu taşımacılık, genel olarak tren, otobüs, tramvay, troleybüs, metro için kullanılsa da, havayolları, feribotlar ve dolmuşları da kapsamakta, halkın bir yerden başka bir yere ulaşımını sağlamayı amaçlamaktadır. Personel ve öğrenci taşımacılığı da Türkiye'de toplu taşımacılığa özel sektörün katkılarının bir göstergesidir (@Wikipedia:2021).

İzmir Türkiye’nin 3. büyük ili olması sebebiyle ulaşım ağı gelişmiştir. Günümüzün yadsınamaz gerçeklerinden birisi olan toplu ulaşım büyük şehirlerde dikkate değer ölçüde önem arz etmekle beraber yıllardır süregelen bir devinim içerisinde olmuştur. Bu çalışmada İzmir Büyükşehir Belediye'sinin veritabanından erişilen ulaşım hatlarının 2015-2023 tarihleri aralığındaki gün bazlı genel biniş raporları kullanılmıştır.


## Çalışmanın Amacı
Bu çalışmada İzmir’de 2015-2023 yılları arasında biniş sayılarının yer aldığı veri seti incelenerek 2024-2026 yıllarındaki biniş sayıları öngörülmesi hedeflenmektedir. Çalışmadan elde edilen bulguların İzmir’deki vatandaşların toplu taşıma kullanım eğilimlerine göre sefer sayısının düzenlenmesine yardımcı olacağı düşünülmektedir.

## Literatür 
Literatür taraması sonucunda büyük şehirlerde toplu taşıma kullanmanın hem gelecek için katkılarına hem de gelecek için zorluklarına değinilmiştir. Bunun yanı sıra bu sorunlara çözüm olanakları sunulmuştur. @Leung:2021 çalışmasında akıllı şehirler için toplu taşımadaki son yeniliklere ve gelecekteki zorluklarına değinmiştir. Aynı zamanda hizmetlerin amacına ve toplu taşıma hizmetini sağlamanın maliyeti üzerinde durulmuştur. @Khan:2022 çalışmalarında otobüs gruplaşmasının azaltılması üzerinde durulmuştur. Otobüs gruplaşması probleminin çözümü için durma-atlama yöntemi sunulmuştur. Bu yöntemdeki çözüm yolu ise hedef sapmadan gidiş yolunu en aza indirmektir. @Karabulut:2017 ise yapmış olduğu çalışmada artan nüfus ve araç sayısı yüzünden trafik sorunları ve çözüm yollarına İzmir özelinde değinilmiştir. Bunun yanı sıra @Hidalgo:2010 incelemesinde toplu taşımanın modernleştirilmesinden bahsetmiştir. Bu incelemede baz alınan Latin Amerika ve Asya’daki otobüs iyileştirmelerinden çıkarılan derslerdir.



\newpage
# Kaynakça {#references}
<div id="refs"></div>

